from machine import Pin
from time import sleep

delay = .25
pin1 = Pin(12, Pin.OUT)
pin2 = Pin(13, Pin.OUT)
pin3 = Pin(16, Pin.OUT)
pin4 = Pin(17, Pin.OUT)



while True:
    pin1.value(0)
    pin2.value(0)
    pin3.value(0)
    pin4.value(0)
    sleep(delay)
    pin1.value(0)
    pin2.value(0)
    pin3.value(0)
    pin4.value(1)
    sleep(delay)
    pin1.value(0)
    pin2.value(0)
    pin3.value(1)
    pin4.value(0)
    sleep(delay)
    pin1.value(0)
    pin2.value(0)
    pin3.value(1)
    pin4.value(1)
    sleep(delay)
    pin1.value(0)
    pin2.value(1)
    pin3.value(0)
    pin4.value(0)
    sleep(delay)
    pin1.value(0)
    pin2.value(1)
    pin3.value(0)
    pin4.value(1)
    sleep(delay)
    pin1.value(0)
    pin2.value(1)
    pin3.value(1)
    pin4.value(0)
    sleep(delay)
    pin1.value(0)
    pin2.value(1)
    pin3.value(1)
    pin4.value(1)
    sleep(delay)
    pin1.value(1)
    pin2.value(0)
    pin3.value(0)
    pin4.value(0)
    sleep(delay)
    pin1.value(1)
    pin2.value(0)
    pin3.value(0)
    pin4.value(1)
    sleep(delay)
    pin1.value(1)
    pin2.value(0)
    pin3.value(1)
    pin4.value(0)
    sleep(delay)
    pin1.value(1)
    pin2.value(0)
    pin3.value(1)
    pin4.value(1)
    sleep(delay)
    pin1.value(1)
    pin2.value(1)
    pin3.value(0)
    pin4.value(0)
    sleep(delay)
    pin1.value(1)
    pin2.value(1)
    pin3.value(0)
    pin4.value(1)
    sleep(delay)
    pin1.value(1)
    pin2.value(1)
    pin3.value(1)
    pin4.value(0)
    sleep(delay)
    pin1.value(1)
    pin2.value(1)
    pin3.value(1)
    pin4.value(1)
    sleep(delay)